# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkeditor', '0002_auto_20161025_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='networkconnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkid', models.IntegerField()),
                ('LatLong', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ConnectedPoints', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
