# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkeditor', '0006_networkconn'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkconn',
            name='LatLongId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
