# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkeditor', '0007_networkconn_latlongid'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkconn',
            name='LatLongx',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkconn',
            name='LatLongy',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
